import { BRAND_PAINT, TEAM_PAINT } from "./visualPaintCatalog.mjs";

const ALL_BRAND_ITEMS = [
  { id: "burger-king", slug: "burgerking", label: "Burger King", assetFile: "burger-king.png", paint: { h: 24, s: 86, v: 92 } },
  { id: "kfc", slug: "kfc", label: "KFC", assetFile: "kfc.png", paint: { h: 356, s: 82, v: 86 } },
  { id: "ikea", slug: "ikea", label: "IKEA", assetFile: "ikea.png", paint: { h: 218, s: 86, v: 80 } },
  { id: "mcdonalds", slug: "mcdonalds", label: "McDonald's", assetFile: "mcdonalds.png", paint: { h: 5, s: 86, v: 90 } },
  { id: "coca-cola", slug: "cocacola", label: "Coca-Cola", assetFile: "coca-cola.png", paint: { h: 357, s: 88, v: 82 } },
  { id: "nike", slug: "nike", label: "Nike", assetFile: "nike.png", paint: { h: 20, s: 100, v: 98 } },
  { id: "adidas", slug: "adidas", label: "Adidas", assetFile: "adidas.png", paint: { h: 201, s: 100, v: 68 } },
  { id: "apple", slug: "apple", label: "Apple", assetFile: "apple.png", paint: { h: 215, s: 10, v: 42 } },
  { id: "google", slug: "google", label: "Google", assetFile: "google.png", paint: { h: 218, s: 78, v: 88 } },
  { id: "netflix", slug: "netflix", label: "Netflix", assetFile: "netflix.png", paint: { h: 356, s: 86, v: 76 } },
  { id: "spotify", slug: "spotify", label: "Spotify", assetFile: "spotify.png", paint: { h: 141, s: 78, v: 72 } },
  { id: "starbucks", slug: "starbucks", label: "Starbucks", assetFile: "starbucks.png", paint: { h: 157, s: 70, v: 52 } },
  { id: "shell", slug: "shell", label: "Shell", assetFile: "shell.png", paint: { h: 42, s: 90, v: 92 } },
  { id: "samsung", slug: "samsung", label: "Samsung", assetFile: "samsung.png", paint: { h: 226, s: 80, v: 67 } },
  { id: "ebay", slug: "ebay", label: "eBay", assetFile: "ebay.png", paint: { h: 217, s: 80, v: 84 } },
  { id: "bmw", slug: "bmw", label: "BMW", assetFile: "bmw.png", paint: { h: 205, s: 76, v: 76 } },
  { id: "ferrari", slug: "ferrari", label: "Ferrari", assetFile: "ferrari.png", paint: { h: 4, s: 92, v: 88 } },
  { id: "puma", slug: "puma", label: "Puma", assetFile: "puma.png", paint: { h: 348, s: 100, v: 90 } },
  { id: "youtube", slug: "youtube", label: "YouTube", assetFile: "youtube.png", paint: { h: 0, s: 88, v: 92 } },
  { id: "xbox", slug: "xbox", label: "Xbox", assetFile: "xbox.png", paint: { h: 125, s: 80, v: 72 } },
  // Keep the source hashes as stable ids while exposing the actual brand names.
  ...[
    ["580b57fbd9996e24bc43bdf2.png", "Android", { h: 102, s: 77, v: 72 }],
    ["580b57fcd9996e24bc43c1f2.png", "Sprite", { h: 150, s: 80, v: 75 }],
    ["580b57fcd9996e24bc43c486.png", "Koenigsegg", { h: 208, s: 38, v: 50 }],
    ["580b57fcd9996e24bc43c48a.png", "Land Rover", { h: 158, s: 72, v: 45 }],
    ["580b57fcd9996e24bc43c4d8.png", "Paris Saint-Germain", { h: 221, s: 77, v: 70 }],
    ["580b57fcd9996e24bc43c4df.png", "Arsenal", { h: 355, s: 85, v: 85 }],
    ["580b57fcd9996e24bc43c4e1.png", "Chelsea", { h: 215, s: 85, v: 72 }],
    ["580b57fcd9996e24bc43c4e4.png", "Aston Villa", { h: 236, s: 65, v: 65 }],
    ["580b57fcd9996e24bc43c4e5.png", "Liverpool", { h: 354, s: 85, v: 75 }],
    ["580b57fcd9996e24bc43c4e7.png", "Manchester United", { h: 0, s: 85, v: 80 }],
    ["580b57fcd9996e24bc43c4ee.png", "Tottenham Hotspur", { h: 218, s: 76, v: 53 }],
    ["580b57fcd9996e24bc43c521.png", "Instagram", { h: 327, s: 80, v: 85 }],
    ["580b57fcd9996e24bc43c52a.png", "Facebook", { h: 221, s: 73, v: 74 }],
    ["580b57fcd9996e24bc43c53e.png", "Twitter", { h: 203, s: 88, v: 92 }],
    ["580b57fcd9996e24bc43c540.png", "Twitch", { h: 265, s: 72, v: 72 }],
    ["580b57fcd9996e24bc43c541.png", "Vine", { h: 153, s: 78, v: 74 }],
    ["580b585b2edbce24c47b2c48.png", "Chevrolet", { h: 45, s: 90, v: 90 }],
    ["580b585b2edbce24c47b2c67.png", "Ford", { h: 216, s: 82, v: 70 }],
    ["580b585b2edbce24c47b2c89.png", "Lamborghini", { h: 104, s: 80, v: 65 }],
    ["580b585b2edbce24c47b2cac.png", "Porsche", { h: 42, s: 75, v: 85 }],
    ["58428cc1a6515b1e0ad75ab1.png", "Starbucks", { h: 157, s: 70, v: 52 }],
    ["58428defa6515b1e0ad75ab4.png", "NBA", { h: 0, s: 75, v: 76 }],
    ["58428e7da6515b1e0ad75ab5.png", "FedEx", { h: 259, s: 75, v: 64 }],
    ["5842997fa6515b1e0ad75adf.png", "Pizza Hut", { h: 355, s: 82, v: 80 }],
    ["58429f65a6515b1e0ad75aed.png", "Lacoste", { h: 150, s: 72, v: 55 }],
    ["58480979cef1014c0b5e4901.png", "Java", { h: 8, s: 80, v: 76 }],
    ["58480fd7cef1014c0b5e4943.png", "Microsoft", { h: 206, s: 78, v: 80 }],
    ["58482354cef1014c0b5e49c0.png", "Mastercard", { h: 12, s: 85, v: 90 }],
    ["58482ffecef1014c0b5e4a8f.png", "Rockstar Games", { h: 48, s: 90, v: 85 }],
    ["584a9b47b080d7616d298778.png", "Real Madrid", { h: 40, s: 68, v: 92 }],
    ["584a9b63b080d7616d29877a.png", "Atlético Madrid", { h: 354, s: 82, v: 75 }],
    ["584ab0a430d6736bca3d6e11.png", "AS Roma", { h: 8, s: 82, v: 68 }],
    ["584ab15330d6736bca3d6e24.png", "AC Milan", { h: 355, s: 85, v: 76 }],
    ["584d8678367b6a13e54477d3.png", "Borussia Dortmund", { h: 54, s: 92, v: 90 }],
    ["584d8683367b6a13e54477d4.png", "FC Bayern Munich", { h: 350, s: 84, v: 78 }],
    ["58568d224f6ae202fedf2720.png", "Intel", { h: 215, s: 78, v: 76 }],
    ["58718a3c7b7f6103e35c6ce2.png", "Doritos", { h: 4, s: 86, v: 84 }],
    ["589a40d65aa6293a4aac48a7.png", "Oreo", { h: 220, s: 86, v: 72 }],
    ["589a418c5aa6293a4aac48a9.png", "Chupa Chups", { h: 355, s: 82, v: 86 }],
    ["589a41e25aa6293a4aac48ab.png", "Cartoon Network", { h: 211, s: 78, v: 76 }],
    ["589a43a65aa6293a4aac48af.png", "Barbie", { h: 329, s: 74, v: 90 }],
    ["589eef9a64b351149f22a88f.png", "Nutella", { h: 11, s: 72, v: 70 }],
    ["5cb77310a7c7755bf004c0f2.png", "Snickers", { h: 228, s: 78, v: 65 }],
    ["5ead3dc11c42dd0004bbf8b0.png", "LEGO", { h: 0, s: 84, v: 86 }],
    ["6011ca412a08e9000490ab76.png", "Sega", { h: 222, s: 82, v: 78 }],
    ["60895f14d598a5000448ea99.png", "Nvidia", { h: 113, s: 80, v: 74 }],
    ["608ae9c60517f5000437cce7.png", "New Balance", { h: 350, s: 75, v: 80 }],
    ["6092d716e4801d000467a0d3.png", "WhatsApp", { h: 145, s: 76, v: 72 }],
    ["6095213753a8bf00040ff3a5.png", "Riot Games", { h: 0, s: 80, v: 82 }],
    ["6102d90fa849c40004f9a133.png", "Subway", { h: 80, s: 80, v: 76 }],
    ["6102dadda849c40004f9a13b.png", "Xiaomi", { h: 6, s: 82, v: 84 }],
    ["612a38397c7c75000443b28a.png", "Monster Energy", { h: 111, s: 80, v: 74 }],
    ["6160562276000b00045a7d97.png", "Amazon", { h: 28, s: 82, v: 86 }],
    ["61fa8c45eec4c40004bacd48.png", "Domino's", { h: 223, s: 78, v: 74 }],
    ["61fbfef03cf0e70004222064.png", "Fanta", { h: 25, s: 88, v: 90 }],
    ["621f8ba5654abf384c30d624.png", "Pepsi", { h: 218, s: 80, v: 74 }],
    ["622f3f23ae7f8f3715381b2e.png", "Popeyes", { h: 22, s: 84, v: 86 }],
    ["62b2265e038aad4d3ed7ca4b.png", "Discord", { h: 233, s: 72, v: 82 }],
    ["pngwing.com.png", "Red Bull", { h: 220, s: 80, v: 78 }],
  ].map(([assetFile, label, paint]) => ({
    id: `asset-${assetFile.replace(/\.png$/, "")}`,
    slug: assetFile.replace(/\.png$/, ""),
    label,
    assetFile,
    paint,
  })),
];

const TEAM_LABELS = new Set([
  "NBA",
  "Paris Saint-Germain",
  "Arsenal",
  "Chelsea",
  "Aston Villa",
  "Liverpool",
  "Manchester United",
  "Tottenham Hotspur",
  "Real Madrid",
  "Atlético Madrid",
  "AS Roma",
  "AC Milan",
  "Borussia Dortmund",
  "FC Bayern Munich",
]);

const NEW_BRAND_ITEMS = [
  ["facebook", "Facebook"], ["amazon", "Amazon"], ["pepsi", "Pepsi"], ["fanta", "Fanta"], ["discord", "Discord"],
  ["steam", "Steam"], ["riot-games", "Riot Games"], ["nvidia", "Nvidia"], ["instagram", "Instagram"], ["xbox", "Xbox"],
  ["google", "Google"], ["google-chrome", "Google Chrome"], ["prime-video", "Prime Video"], ["carrefour", "Carrefour"], ["dominos", "Domino's"],
  ["ebay", "eBay"], ["doritos", "Doritos"], ["lays", "Lay's"], ["cheetos", "Cheetos"], ["ruffles", "Ruffles"],
  ["fedex", "FedEx"], ["ikea", "IKEA"], ["intel", "Intel"], ["android", "Android"], ["kfc", "KFC"],
  ["lacoste", "Lacoste"], ["twitter", "Twitter"], ["twitch", "Twitch"], ["subway", "Subway"], ["sprite", "Sprite"],
  ["starbucks", "Starbucks"], ["spotify", "Spotify"], ["shell", "Shell"], ["bp", "BP"], ["apple", "Apple"],
  ["pepsi-globe", "Pepsi"], ["snickers", "Snickers"], ["samsung", "Samsung"], ["lg", "LG"], ["rockstar-games", "Rockstar Games"],
  ["red-bull", "Red Bull"], ["popeyes", "Popeyes"], ["netflix", "Netflix"], ["snapchat", "Snapchat"], ["mastercard", "Mastercard"],
  ["burger-king-round", "Burger King"], ["visa", "Visa"], ["microsoft", "Microsoft"], ["monster-energy", "Monster Energy"], ["lego", "LEGO"],
  ["burger-king", "Burger King"], ["mcdonalds", "McDonald's"], ["chupa-chups", "Chupa Chups"], ["coca-cola", "Coca-Cola"], ["youtube", "YouTube"],
].map(([slug, label]) => ({
  id: slug,
  slug,
  label,
  assetFile: `${slug}.png`,
  paint: BRAND_PAINT[slug],
}));

export const BRAND_ITEMS = NEW_BRAND_ITEMS;

const NEW_TEAM_ITEMS = [
  ["augsburg", "Augsburg"],
  ["bayer-leverkusen", "Bayer Leverkusen"],
  ["bayern-munich", "Bayern München"],
  ["borussia-dortmund", "Borussia Dortmund"],
  ["borussia-monchengladbach", "Borussia Mönchengladbach"],
  ["eintracht-frankfurt", "Eintracht Frankfurt"],
  ["freiburg", "Freiburg"],
  ["hamburger-sv", "Hamburger Sv"],
  ["hoffenheim", "Hoffenheim"],
  ["koln", "Köln"],
  ["mainz-05", "Mainz 05"],
  ["paderborn", "Paderborn"],
  ["rb-leipzig", "RB Leipzig"],
  ["schalke-04", "Schalke 04"],
  ["elversberg", "Sv Elversberg"],
  ["union-berlin", "Union Berlin"],
  ["vfb-stuttgart", "VfB Stuttgart"],
  ["werder-bremen", "Werder Bremen"],
  ["athletic-club", "Athletic Club"],
  ["atletico-madrid", "Atletico Madrid"],
  ["barcelona", "Barcelona"],
  ["celta-vigo", "Celta"],
  ["deportivo-la-coruna", "Deportivo La Coruña"],
  ["deportivo-alaves", "Deportivo"],
  ["elche", "Elche"],
  ["espanyol", "Espanyol"],
  ["getafe", "Getafe"],
  ["levante", "Levante"],
  ["malaga", "Malaga"],
  ["osasuna", "Osasuna"],
  ["racing", "Racing"],
  ["rayo-vallecano", "Rayo Vallecano"],
  ["real-betis", "Real Betis"],
  ["real-madrid", "Real Madrid"],
  ["real-sociedad", "Real Sociedad"],
  ["sevilla", "Sevilla"],
  ["valencia", "Valencia"],
  ["villarreal", "Villarreal"],
  ["angers", "Angers"],
  ["monaco", "AS Monaco"],
  ["auxerre", "Auxerre"],
  ["brest", "Brest"],
  ["le-havre-ac", "Le Havre Ac"],
  ["le-mans", "Le Mans"],
  ["lille", "Lille"],
  ["lorient", "Lorient"],
  ["lyon", "Lyon"],
  ["nice", "Nice"],
  ["paris-fc", "Paris Fc"],
  ["psg", "Paris Saint-Germain"],
  ["rc-lens", "RC Lens"],
  ["rc-strasbourg-alsace", "RC Strasbourg Alsace"],
  ["rennes", "Rennes"],
  ["toulouse", "Toulouse"],
  ["troyes", "Troyes"],
  ["arsenal", "Arsenal"],
  ["aston-villa", "Aston Villa"],
  ["bournemouth", "Bournemouth"],
  ["brentford", "Brentford"],
  ["brighton", "Brighton"],
  ["chelsea", "Chelsea"],
  ["coventry-city", "Coventry City"],
  ["crystal-palace", "Crystal Palace"],
  ["everton", "Everton"],
  ["fulham", "Fulham"],
  ["hull-city", "Hull City"],
  ["ipswich-town", "Ipswich"],
  ["leeds-united", "Leeds United"],
  ["liverpool", "Liverpool"],
  ["manchester-city", "Manchester City"],
  ["manchester-united", "Manchester United"],
  ["newcastle-united", "Newcastle"],
  ["nottingham-forest", "Nottingham Forest"],
  ["sunderland", "Sunderland"],
  ["tottenham-hotspur", "Tottenham"],
  ["atalanta", "Atalanta"],
  ["bologna", "Bologna"],
  ["cagliari", "Cagliari"],
  ["como", "Como 1907"],
  ["fiorentina", "Fiorentina"],
  ["frosinone", "Frosinone"],
  ["genoa", "Genoa"],
  ["inter", "Inter"],
  ["juventus", "Juventus"],
  ["lazio", "Lazio"],
  ["lecce", "Lecce"],
  ["ac-milan", "Milan"],
  ["monza", "Monza"],
  ["napoli", "Napoli"],
  ["parma", "Parma"],
  ["roma", "Roma"],
  ["sassuolo", "Sassuolo"],
  ["torino", "Torino"],
  ["udinese", "Udinese"],
  ["venezia", "Venezia"],
  ["alanyaspor", "Alanyaspor"],
  ["antalyaspor", "Antalyaspor"],
  ["basaksehir", "Basaksehir"],
  ["besiktas", "Besiktas"],
  ["bursaspor", "Bursaspor"],
  ["corum", "Corum"],
  ["erzurumspor", "Erzurumspor"],
  ["eyupspor", "Eyupspor"],
  ["fenerbahce", "Fenerbahce"],
  ["galatasaray", "Galatasaray"],
  ["gaziantep", "Gaziantep"],
  ["genclerbirligi", "Genclerbirligi"],
  ["goztepe", "Göztepe"],
  ["kasimpasa", "Kasimpasa"],
  ["kayserispor", "Kayserispor"],
  ["kocaelispor", "Kocaelispor"],
  ["konyaspor", "Konyaspor"],
  ["rizespor", "Rizespor"],
  ["samsunspor", "Samsunspor"],
  ["sivasspor", "Sivasspor"],
  ["trabzonspor", "Trabzonspor"],
].map(([slug, label]) => ({
  id: `team-${slug}`,
  slug,
  label,
  assetFile: `${slug}.png`,
  paint: TEAM_PAINT[`team-${slug}`],
}));

const TEAM_LEAGUES = {
  "augsburg": "Bundesliga",
  "bayer-leverkusen": "Bundesliga",
  "bayern-munich": "Bundesliga",
  "borussia-dortmund": "Bundesliga",
  "borussia-monchengladbach": "Bundesliga",
  "eintracht-frankfurt": "Bundesliga",
  "freiburg": "Bundesliga",
  "hamburger-sv": "Bundesliga",
  "hoffenheim": "Bundesliga",
  "koln": "Bundesliga",
  "mainz-05": "Bundesliga",
  "paderborn": "Bundesliga",
  "rb-leipzig": "Bundesliga",
  "schalke-04": "Bundesliga",
  "elversberg": "Bundesliga",
  "union-berlin": "Bundesliga",
  "vfb-stuttgart": "Bundesliga",
  "werder-bremen": "Bundesliga",
  "athletic-club": "La Liga",
  "atletico-madrid": "La Liga",
  "barcelona": "La Liga",
  "celta-vigo": "La Liga",
  "deportivo-la-coruna": "La Liga",
  "deportivo-alaves": "La Liga",
  "elche": "La Liga",
  "espanyol": "La Liga",
  "getafe": "La Liga",
  "levante": "La Liga",
  "malaga": "La Liga",
  "osasuna": "La Liga",
  "racing": "La Liga",
  "rayo-vallecano": "La Liga",
  "real-betis": "La Liga",
  "real-madrid": "La Liga",
  "real-sociedad": "La Liga",
  "sevilla": "La Liga",
  "valencia": "La Liga",
  "villarreal": "La Liga",
  "angers": "Ligue 1",
  "monaco": "Ligue 1",
  "auxerre": "Ligue 1",
  "brest": "Ligue 1",
  "le-havre-ac": "Ligue 1",
  "le-mans": "Ligue 1",
  "lille": "Ligue 1",
  "lorient": "Ligue 1",
  "lyon": "Ligue 1",
  "nice": "Ligue 1",
  "paris-fc": "Ligue 1",
  "psg": "Ligue 1",
  "rc-lens": "Ligue 1",
  "rc-strasbourg-alsace": "Ligue 1",
  "rennes": "Ligue 1",
  "toulouse": "Ligue 1",
  "troyes": "Ligue 1",
  "arsenal": "Premier League",
  "aston-villa": "Premier League",
  "bournemouth": "Premier League",
  "brentford": "Premier League",
  "brighton": "Premier League",
  "chelsea": "Premier League",
  "coventry-city": "Premier League",
  "crystal-palace": "Premier League",
  "everton": "Premier League",
  "fulham": "Premier League",
  "hull-city": "Premier League",
  "ipswich-town": "Premier League",
  "leeds-united": "Premier League",
  "liverpool": "Premier League",
  "manchester-city": "Premier League",
  "manchester-united": "Premier League",
  "newcastle-united": "Premier League",
  "nottingham-forest": "Premier League",
  "sunderland": "Premier League",
  "tottenham-hotspur": "Premier League",
  "atalanta": "Seria A",
  "bologna": "Seria A",
  "cagliari": "Seria A",
  "como": "Seria A",
  "fiorentina": "Seria A",
  "frosinone": "Seria A",
  "genoa": "Seria A",
  "inter": "Seria A",
  "juventus": "Seria A",
  "lazio": "Seria A",
  "lecce": "Seria A",
  "ac-milan": "Seria A",
  "monza": "Seria A",
  "napoli": "Seria A",
  "parma": "Seria A",
  "roma": "Seria A",
  "sassuolo": "Seria A",
  "torino": "Seria A",
  "udinese": "Seria A",
  "venezia": "Seria A",
  "alanyaspor": "Süper Lig",
  "antalyaspor": "Süper Lig",
  "basaksehir": "Süper Lig",
  "besiktas": "Süper Lig",
  "bursaspor": "Süper Lig",
  "corum": "Süper Lig",
  "erzurumspor": "Süper Lig",
  "eyupspor": "Süper Lig",
  "fenerbahce": "Süper Lig",
  "galatasaray": "Süper Lig",
  "gaziantep": "Süper Lig",
  "genclerbirligi": "Süper Lig",
  "goztepe": "Süper Lig",
  "kasimpasa": "Süper Lig",
  "kayserispor": "Süper Lig",
  "kocaelispor": "Süper Lig",
  "konyaspor": "Süper Lig",
  "rizespor": "Süper Lig",
  "samsunspor": "Süper Lig",
  "sivasspor": "Süper Lig",
  "trabzonspor": "Süper Lig",
};

for (const team of NEW_TEAM_ITEMS) team.league = TEAM_LEAGUES[team.slug] || "Other";

export const TEAM_ITEMS = [...NEW_TEAM_ITEMS].sort((left, right) =>
  `${left.league}-${left.label}`.localeCompare(`${right.league}-${right.label}`),
);

export const DEFAULT_BRAND_ID = BRAND_ITEMS[0].id;

export function getBrandItem(brandId = DEFAULT_BRAND_ID) {
  return BRAND_ITEMS.find((brand) => brand.id === brandId) || BRAND_ITEMS[0];
}
