const ADVENTURE_TIME_ASSET_ROOT = "public/game-modes/cartoon/adventure-time/assets";
const ADVENTURE_TIME_MASK_ROOT = "public/game-modes/cartoon/adventure-time/masks";
const POWERPUFF_GIRLS_ASSET_ROOT = "public/game-modes/cartoon/powerpuff-girls/assets";
const POWERPUFF_GIRLS_MASK_ROOT = "public/game-modes/cartoon/powerpuff-girls/masks";

export const CARTOON_ITEMS = [
  {
    id: "adventure-time-gunter-penguin",
    label: "Gunter",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 48, s: 20, v: 97 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-gunter-penguin.jpg`,
    sourceTitle: "adventure-time-gunter-penguin.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-gunter-penguin.png`,
  },
  {
    id: "adventure-time-bmo",
    label: "BMO",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 160, s: 40, v: 81 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-bmo.jpg`,
    sourceTitle: "adventure-time-bmo.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-bmo.png`,
  },
  {
    id: "adventure-time-mustache-ball",
    label: "Mustache Ball",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 32, s: 65, v: 74 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-mustache-ball.jpg`,
    sourceTitle: "adventure-time-mustache-ball.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-mustache-ball.png`,
  },
  {
    id: "adventure-time-lumpy-space-princess",
    label: "Lumpy Space Princess",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 288, s: 40, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-lumpy-space-princess.jpg`,
    sourceTitle: "adventure-time-lumpy-space-princess.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-lumpy-space-princess.png`,
  },
  {
    id: "adventure-time-princess-bubblegum-and-finn",
    label: "Princess Bubblegum",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 304, s: 80, v: 95 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-princess-bubblegum-and-finn.jpg`,
    sourceTitle: "adventure-time-princess-bubblegum-and-finn.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-princess-bubblegum-and-finn.png`,
  },
  {
    id: "adventure-time-candy-kingdom-party",
    label: "Candy Kingdom Party",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 352, s: 91, v: 87 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-candy-kingdom-party.jpg`,
    sourceTitle: "adventure-time-candy-kingdom-party.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-candy-kingdom-party.png`,
  },
  {
    id: "adventure-time-finn-and-jake",
    label: "Finn and Jake",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 192, s: 100, v: 82 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-and-jake.jpg`,
    sourceTitle: "adventure-time-finn-and-jake.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-and-jake.png`,
  },
  {
    id: "adventure-time-earl-of-lemongrab",
    label: "Earl of Lemongrab",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 56, s: 59, v: 68 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-earl-of-lemongrab.jpg`,
    sourceTitle: "adventure-time-earl-of-lemongrab.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-earl-of-lemongrab.png`,
  },
  {
    id: "adventure-time-glowing-room-ghost",
    label: "Glowing Room Ghost",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 16, s: 47, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-glowing-room-ghost.jpg`,
    sourceTitle: "adventure-time-glowing-room-ghost.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-glowing-room-ghost.png`,
  },
  {
    id: "adventure-time-lady-rainicorn",
    label: "Lady Rainicorn",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 64, s: 44, v: 97 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-lady-rainicorn.jpg`,
    sourceTitle: "adventure-time-lady-rainicorn.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-lady-rainicorn.png`,
  },
  {
    id: "adventure-time-marceline-book",
    label: "Marceline Book",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 216, s: 55, v: 48 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-marceline-book.jpg`,
    sourceTitle: "adventure-time-marceline-book.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-marceline-book.png`,
  },
  {
    id: "adventure-time-susan-strong",
    label: "Susan Strong",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 16, s: 26, v: 94 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-susan-strong.jpg`,
    sourceTitle: "adventure-time-susan-strong.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-susan-strong.png`,
  },
  {
    id: "adventure-time-finn-and-fern",
    label: "Finn and Fern",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 88, s: 67, v: 71 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-and-fern.jpg`,
    sourceTitle: "adventure-time-finn-and-fern.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-and-fern.png`,
  },
  {
    id: "adventure-time-finn-and-flame-princess-hug",
    label: "Finn and Flame Princess",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 21, s: 90, v: 98 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-and-flame-princess-hug.jpg`,
    sourceTitle: "adventure-time-finn-and-flame-princess-hug.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-and-flame-princess-hug.png`,
  },
  {
    id: "adventure-time-marceline-guitar",
    label: "Marceline Guitar",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 350, s: 74, v: 33 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-marceline-guitar.jpg`,
    sourceTitle: "adventure-time-marceline-guitar.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-marceline-guitar.png`,
  },
  {
    id: "adventure-time-jake-snow-snack",
    label: "Jake Snow Snack",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 53, s: 94, v: 95 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-jake-snow-snack.jpg`,
    sourceTitle: "adventure-time-jake-snow-snack.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-jake-snow-snack.png`,
  },
  {
    id: "adventure-time-tree-trunks-kitchen",
    label: "Tree Trunks Kitchen",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 59, s: 59, v: 96 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-tree-trunks-kitchen.jpg`,
    sourceTitle: "adventure-time-tree-trunks-kitchen.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-tree-trunks-kitchen.png`,
  },
  {
    id: "adventure-time-cinnamon-bun-party",
    label: "Cinnamon Bun Party",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 30, s: 57, v: 90 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-cinnamon-bun-party.jpg`,
    sourceTitle: "adventure-time-cinnamon-bun-party.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-cinnamon-bun-party.png`,
  },
  {
    id: "adventure-time-neptr-running",
    label: "NEPTR Running",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 132, s: 19, v: 45 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-neptr-running.jpg`,
    sourceTitle: "adventure-time-neptr-running.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-neptr-running.png`,
  },
  {
    id: "adventure-time-business-men",
    label: "Business Men",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 127, s: 6, v: 74 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-business-men.jpg`,
    sourceTitle: "adventure-time-business-men.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-business-men.png`,
  },
  {
    id: "adventure-time-ice-king-and-gunter",
    label: "Ice King and Gunter",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 90, s: 22, v: 90 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-ice-king-and-gunter.jpg`,
    sourceTitle: "adventure-time-ice-king-and-gunter.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-ice-king-and-gunter.png`,
  },
  {
    id: "adventure-time-finn-jake-pillow",
    label: "Finn Jake Pillow",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 46, s: 21, v: 91 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-jake-pillow.jpg`,
    sourceTitle: "adventure-time-finn-jake-pillow.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-jake-pillow.png`,
  },
  {
    id: "adventure-time-ice-king-clouds",
    label: "Ice King Clouds",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 239, s: 79, v: 75 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-ice-king-clouds.jpg`,
    sourceTitle: "adventure-time-ice-king-clouds.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-ice-king-clouds.png`,
  },
  {
    id: "adventure-time-princess-bubblegum-rainicorn",
    label: "Princess Bubblegum Rainicorn",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 7, s: 26, v: 74 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-princess-bubblegum-rainicorn.jpg`,
    sourceTitle: "adventure-time-princess-bubblegum-rainicorn.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-princess-bubblegum-rainicorn.png`,
  },
  {
    id: "powerpuff-girls-bubbles-heart",
    label: "Bubbles",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 207, s: 43, v: 95 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-bubbles-heart.jpg`,
    sourceTitle: "powerpuff-girls-bubbles-heart.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-bubbles-heart.png`,
  },
  {
    id: "powerpuff-girls-professor-utonium-lab",
    label: "Professor Utonium",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 36, s: 25, v: 90 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-professor-utonium-lab.jpg`,
    sourceTitle: "powerpuff-girls-professor-utonium-lab.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-professor-utonium-lab.png`,
  },
  {
    id: "powerpuff-girls-buttercup-clouds",
    label: "Buttercup",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 107, s: 45, v: 88 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-buttercup-clouds.jpg`,
    sourceTitle: "powerpuff-girls-buttercup-clouds.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-buttercup-clouds.png`,
  },
  {
    id: "powerpuff-girls-mayor-couch",
    label: "Mayor",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 33, s: 20, v: 90 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-mayor-couch.jpg`,
    sourceTitle: "powerpuff-girls-mayor-couch.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-mayor-couch.png`,
  },
  {
    id: "powerpuff-girls-blossom-couch",
    label: "Blossom",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 330, s: 62, v: 96 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-blossom-couch.jpg`,
    sourceTitle: "powerpuff-girls-blossom-couch.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-blossom-couch.png`,
  },
  {
    id: "powerpuff-girls-mojo-jojo-dog-walk",
    label: "Mojo Jojo",
    series: "Powerpuff Girls",
    paintLabel: "cartoon",
    paint: { h: 301, s: 27, v: 44 },
    sourcePath: `${POWERPUFF_GIRLS_ASSET_ROOT}/powerpuff-girls-mojo-jojo-dog-walk.jpg`,
    sourceTitle: "powerpuff-girls-mojo-jojo-dog-walk.jpg",
    maskPath: `${POWERPUFF_GIRLS_MASK_ROOT}/powerpuff-girls-mojo-jojo-dog-walk.png`,
  },
];
