const ADVENTURE_TIME_ASSET_ROOT = "public/game-modes/cartoon/adventure-time/assets";
const ADVENTURE_TIME_MASK_ROOT = "public/game-modes/cartoon/adventure-time/masks";

export const CARTOON_ITEMS = [
  {
    id: "adventure-time-gunter-penguin",
    label: "Gunter",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 48, s: 20, v: 97 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-gunter-penguin.jpg`,
    sourceTitle: "adventure-time-gunter-penguin.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-gunter-penguin.png`,
  },
  {
    id: "adventure-time-galactic-owl",
    label: "Galactic Owl",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 48, s: 92, v: 56 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-galactic-owl.jpg`,
    sourceTitle: "adventure-time-galactic-owl.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-galactic-owl.png`,
  },
  {
    id: "adventure-time-marceline",
    label: "Marceline",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 0, s: 99, v: 43 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-marceline.jpg`,
    sourceTitle: "adventure-time-marceline.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-marceline.png`,
  },
  {
    id: "adventure-time-tree-trunks-night",
    label: "Tree Trunks",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 240, s: 22, v: 71 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-tree-trunks-night.jpg`,
    sourceTitle: "adventure-time-tree-trunks-night.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-tree-trunks-night.png`,
  },
  {
    id: "adventure-time-bmo",
    label: "BMO",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 160, s: 40, v: 81 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-bmo.jpg`,
    sourceTitle: "adventure-time-bmo.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-bmo.png`,
  },
  {
    id: "adventure-time-tree-trunks-closeup",
    label: "Tree Trunks Closeup",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 0, s: 36, v: 54 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-tree-trunks-closeup.jpg`,
    sourceTitle: "adventure-time-tree-trunks-closeup.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-tree-trunks-closeup.png`,
  },
  {
    id: "adventure-time-mustache-ball",
    label: "Mustache Ball",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 32, s: 65, v: 74 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-mustache-ball.jpg`,
    sourceTitle: "adventure-time-mustache-ball.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-mustache-ball.png`,
  },
  {
    id: "adventure-time-lumpy-space-princess",
    label: "Lumpy Space Princess",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 288, s: 40, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-lumpy-space-princess.jpg`,
    sourceTitle: "adventure-time-lumpy-space-princess.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-lumpy-space-princess.png`,
  },
  {
    id: "adventure-time-lemongrab-closeup",
    label: "Lemongrab Closeup",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 64, s: 59, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-lemongrab-closeup.jpg`,
    sourceTitle: "adventure-time-lemongrab-closeup.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-lemongrab-closeup.png`,
  },
  {
    id: "adventure-time-princess-bubblegum-and-finn",
    label: "Princess Bubblegum",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 304, s: 80, v: 95 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-princess-bubblegum-and-finn.jpg`,
    sourceTitle: "adventure-time-princess-bubblegum-and-finn.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-princess-bubblegum-and-finn.png`,
  },
  {
    id: "adventure-time-neptr-robot",
    label: "NEPTR",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 184, s: 25, v: 45 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-neptr-robot.jpg`,
    sourceTitle: "adventure-time-neptr-robot.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-neptr-robot.png`,
  },
  {
    id: "adventure-time-candy-kingdom-party",
    label: "Candy Kingdom Party",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 352, s: 91, v: 87 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-candy-kingdom-party.jpg`,
    sourceTitle: "adventure-time-candy-kingdom-party.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-candy-kingdom-party.png`,
  },
  {
    id: "adventure-time-ice-king",
    label: "Ice King",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 240, s: 100, v: 85 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-ice-king.jpg`,
    sourceTitle: "adventure-time-ice-king.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-ice-king.png`,
  },
  {
    id: "adventure-time-finn-and-jake",
    label: "Finn and Jake",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 192, s: 100, v: 82 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-and-jake.jpg`,
    sourceTitle: "adventure-time-finn-and-jake.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-and-jake.png`,
  },
  {
    id: "adventure-time-jake-violin",
    label: "Jake",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 56, s: 93, v: 95 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-jake-violin.jpg`,
    sourceTitle: "adventure-time-jake-violin.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-jake-violin.png`,
  },
  {
    id: "adventure-time-earl-of-lemongrab",
    label: "Earl of Lemongrab",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 56, s: 59, v: 68 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-earl-of-lemongrab.jpg`,
    sourceTitle: "adventure-time-earl-of-lemongrab.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-earl-of-lemongrab.png`,
  },
  {
    id: "adventure-time-glowing-room-ghost",
    label: "Glowing Room Ghost",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 16, s: 47, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-glowing-room-ghost.jpg`,
    sourceTitle: "adventure-time-glowing-room-ghost.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-glowing-room-ghost.png`,
  },
  {
    id: "adventure-time-lady-rainicorn",
    label: "Lady Rainicorn",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 64, s: 44, v: 97 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-lady-rainicorn.jpg`,
    sourceTitle: "adventure-time-lady-rainicorn.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-lady-rainicorn.png`,
  },
  {
    id: "adventure-time-marceline-book",
    label: "Marceline Book",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 216, s: 55, v: 48 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-marceline-book.jpg`,
    sourceTitle: "adventure-time-marceline-book.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-marceline-book.png`,
  },
  {
    id: "adventure-time-flame-princess",
    label: "Flame Princess",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 16, s: 91, v: 99 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-flame-princess.jpg`,
    sourceTitle: "adventure-time-flame-princess.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-flame-princess.png`,
  },
  {
    id: "adventure-time-susan-strong",
    label: "Susan Strong",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 16, s: 26, v: 94 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-susan-strong.jpg`,
    sourceTitle: "adventure-time-susan-strong.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-susan-strong.png`,
  },
  {
    id: "adventure-time-finn-and-fern",
    label: "Finn and Fern",
    series: "Adventure Time",
    paintLabel: "cartoon",
    paint: { h: 88, s: 67, v: 71 },
    sourcePath: `${ADVENTURE_TIME_ASSET_ROOT}/adventure-time-finn-and-fern.jpg`,
    sourceTitle: "adventure-time-finn-and-fern.jpg",
    maskPath: `${ADVENTURE_TIME_MASK_ROOT}/adventure-time-finn-and-fern.png`,
  },
];
