export const GAME_FAMILY_MODE_IDS = Object.freeze({
  color: Object.freeze([
    "normal",
    "endless",
    "flash",
    "sequence",
    "timed",
    "gradient",
    "blend",
    "decoy",
    "rush",
    "elimination",
    "blind",
    "spot",
  ]),
  flag: Object.freeze(["normal", "endless", "timed", "rush", "elimination"]),
  cartoon: Object.freeze(["normal", "endless", "timed", "rush", "elimination"]),
  brand: Object.freeze(["normal", "endless", "timed", "rush", "elimination"]),
  team: Object.freeze(["normal", "endless", "timed", "rush", "elimination"]),
});

export const MULTIPLAYER_GAME_FAMILY_MODE_IDS = Object.freeze({
  color: Object.freeze([
    "normal",
    "flash",
    "sequence",
    "timed",
    "gradient",
    "blend",
    "decoy",
    "rush",
    "elimination",
    "blind",
    "spot",
  ]),
  flag: Object.freeze(["normal", "timed", "rush", "elimination"]),
  cartoon: Object.freeze(["normal", "timed", "rush", "elimination"]),
  brand: Object.freeze(["normal", "timed", "rush", "elimination"]),
  team: Object.freeze(["normal", "timed", "rush", "elimination"]),
});
