// Generated by the visual scene build scripts. Values are measured from the
// original artwork and are the neutral anchor for the shared delta renderer.
export const BRAND_PAINT = {
  "facebook": {
    "h": 220,
    "s": 51,
    "v": 67
  },
  "amazon": {
    "h": 32,
    "s": 12,
    "v": 30
  },
  "pepsi": {
    "h": 337,
    "s": 64,
    "v": 82
  },
  "fanta": {
    "h": 241,
    "s": 45,
    "v": 75
  },
  "discord": {
    "h": 231,
    "s": 45,
    "v": 100
  },
  "steam": {
    "h": 214,
    "s": 55,
    "v": 53
  },
  "riot-games": {
    "h": 356,
    "s": 80,
    "v": 82
  },
  "nvidia": {
    "h": 82,
    "s": 100,
    "v": 73
  },
  "instagram": {
    "h": 344,
    "s": 52,
    "v": 89
  },
  "xbox": {
    "h": 107,
    "s": 29,
    "v": 77
  },
  "google": {
    "h": 287,
    "s": 78,
    "v": 92
  },
  "google-chrome": {
    "h": 57,
    "s": 73,
    "v": 85
  },
  "prime-video": {
    "h": 196,
    "s": 79,
    "v": 65
  },
  "carrefour": {
    "h": 225,
    "s": 96,
    "v": 62
  },
  "dominos": {
    "h": 302,
    "s": 71,
    "v": 83
  },
  "ebay": {
    "h": 44,
    "s": 92,
    "v": 86
  },
  "doritos": {
    "h": 20,
    "s": 40,
    "v": 41
  },
  "lays": {
    "h": 22,
    "s": 41,
    "v": 93
  },
  "cheetos": {
    "h": 44,
    "s": 64,
    "v": 69
  },
  "ruffles": {
    "h": 12,
    "s": 75,
    "v": 87
  },
  "fedex": {
    "h": 341,
    "s": 91,
    "v": 73
  },
  "ikea": {
    "h": 59,
    "s": 100,
    "v": 80
  },
  "intel": {
    "h": 206,
    "s": 100,
    "v": 77
  },
  "android": {
    "h": 76,
    "s": 81,
    "v": 75
  },
  "kfc": {
    "h": 1,
    "s": 53,
    "v": 60
  },
  "lacoste": {
    "h": 138,
    "s": 67,
    "v": 66
  },
  "twitter": {
    "h": 196,
    "s": 100,
    "v": 93
  },
  "twitch": {
    "h": 262,
    "s": 55,
    "v": 61
  },
  "subway": {
    "h": 82,
    "s": 71,
    "v": 73
  },
  "sprite": {
    "h": 181,
    "s": 38,
    "v": 78
  },
  "starbucks": {
    "h": 155,
    "s": 55,
    "v": 68
  },
  "spotify": {
    "h": 141,
    "s": 86,
    "v": 84
  },
  "shell": {
    "h": 29,
    "s": 93,
    "v": 93
  },
  "bp": {
    "h": 106,
    "s": 89,
    "v": 77
  },
  "apple": {
    "h": 33,
    "s": 76,
    "v": 83
  },
  "pepsi-globe": {
    "h": 345,
    "s": 87,
    "v": 84
  },
  "snickers": {
    "h": 258,
    "s": 50,
    "v": 74
  },
  "samsung": {
    "h": 212,
    "s": 80,
    "v": 70
  },
  "lg": {
    "h": 337,
    "s": 81,
    "v": 80
  },
  "rockstar-games": {
    "h": 39,
    "s": 78,
    "v": 79
  },
  "red-bull": {
    "h": 355,
    "s": 66,
    "v": 90
  },
  "popeyes": {
    "h": 8,
    "s": 53,
    "v": 90
  },
  "netflix": {
    "h": 0,
    "s": 100,
    "v": 69
  },
  "snapchat": {
    "h": 57,
    "s": 59,
    "v": 93
  },
  "mastercard": {
    "h": 15,
    "s": 90,
    "v": 90
  },
  "burger-king-round": {
    "h": 8,
    "s": 86,
    "v": 86
  },
  "visa": {
    "h": 206,
    "s": 99,
    "v": 64
  },
  "microsoft": {
    "h": 59,
    "s": 94,
    "v": 91
  },
  "monster-energy": {
    "h": 95,
    "s": 49,
    "v": 47
  },
  "lego": {
    "h": 4,
    "s": 62,
    "v": 72
  },
  "burger-king": {
    "h": 17,
    "s": 86,
    "v": 92
  },
  "mcdonalds": {
    "h": 46,
    "s": 100,
    "v": 100
  },
  "chupa-chups": {
    "h": 37,
    "s": 69,
    "v": 90
  },
  "coca-cola": {
    "h": 0,
    "s": 100,
    "v": 96
  },
  "youtube": {
    "h": 3,
    "s": 71,
    "v": 72
  }
};
export const TEAM_PAINT = {
  "team-athletic-club": {
    "h": 5,
    "s": 16,
    "v": 75
  },
  "team-atletico-madrid": {
    "h": 317,
    "s": 41,
    "v": 64
  },
  "team-barcelona": {
    "h": 25,
    "s": 83,
    "v": 66
  },
  "team-celta-vigo": {
    "h": 340,
    "s": 60,
    "v": 91
  },
  "team-deportivo-alaves": {
    "h": 205,
    "s": 89,
    "v": 65
  },
  "team-elche": {
    "h": 29,
    "s": 53,
    "v": 81
  },
  "team-espanyol": {
    "h": 28,
    "s": 70,
    "v": 86
  },
  "team-getafe": {
    "h": 184,
    "s": 58,
    "v": 74
  },
  "team-girona": {
    "h": 9,
    "s": 49,
    "v": 74
  },
  "team-levante": {
    "h": 10,
    "s": 47,
    "v": 44
  },
  "team-mallorca": {
    "h": 25,
    "s": 87,
    "v": 65
  },
  "team-osasuna": {
    "h": 20,
    "s": 56,
    "v": 71
  },
  "team-rayo-vallecano": {
    "h": 33,
    "s": 31,
    "v": 86
  },
  "team-real-betis": {
    "h": 66,
    "s": 66,
    "v": 82
  },
  "team-real-madrid": {
    "h": 43,
    "s": 68,
    "v": 85
  },
  "team-real-oviedo": {
    "h": 35,
    "s": 52,
    "v": 84
  },
  "team-real-sociedad": {
    "h": 15,
    "s": 63,
    "v": 62
  },
  "team-sevilla": {
    "h": 16,
    "s": 42,
    "v": 83
  },
  "team-valencia": {
    "h": 33,
    "s": 51,
    "v": 71
  },
  "team-villarreal": {
    "h": 29,
    "s": 64,
    "v": 67
  },
  "team-arsenal": {
    "h": 3,
    "s": 72,
    "v": 78
  },
  "team-aston-villa": {
    "h": 54,
    "s": 52,
    "v": 83
  },
  "team-bournemouth": {
    "h": 357,
    "s": 27,
    "v": 55
  },
  "team-brentford": {
    "h": 1,
    "s": 35,
    "v": 63
  },
  "team-brighton": {
    "h": 207,
    "s": 50,
    "v": 83
  },
  "team-burnley": {
    "h": 102,
    "s": 61,
    "v": 83
  },
  "team-chelsea": {
    "h": 210,
    "s": 59,
    "v": 77
  },
  "team-coventry-city": {
    "h": 32,
    "s": 15,
    "v": 78
  },
  "team-crystal-palace": {
    "h": 227,
    "s": 44,
    "v": 75
  },
  "team-everton": {
    "h": 222,
    "s": 55,
    "v": 63
  },
  "team-fulham": {
    "h": 0,
    "s": 12,
    "v": 57
  },
  "team-hull-city": {
    "h": 35,
    "s": 50,
    "v": 57
  },
  "team-ipswich-town": {
    "h": 322,
    "s": 48,
    "v": 76
  },
  "team-leeds-united": {
    "h": 77,
    "s": 82,
    "v": 87
  },
  "team-liverpool": {
    "h": 26,
    "s": 49,
    "v": 77
  },
  "team-manchester-city": {
    "h": 205,
    "s": 42,
    "v": 81
  },
  "team-manchester-united": {
    "h": 24,
    "s": 92,
    "v": 80
  },
  "team-newcastle-united": {
    "h": 177,
    "s": 36,
    "v": 56
  },
  "team-sunderland": {
    "h": 5,
    "s": 41,
    "v": 55
  },
  "team-tottenham-hotspur": {
    "h": 221,
    "s": 9,
    "v": 83
  },
  "team-ac-milan": {
    "h": 0,
    "s": 30,
    "v": 57
  },
  "team-atalanta": {
    "h": 213,
    "s": 21,
    "v": 64
  },
  "team-bologna": {
    "h": 352,
    "s": 68,
    "v": 78
  },
  "team-cagliari": {
    "h": 332,
    "s": 54,
    "v": 76
  },
  "team-como": {
    "h": 2,
    "s": 26,
    "v": 91
  },
  "team-fiorentina": {
    "h": 340,
    "s": 46,
    "v": 80
  },
  "team-frosinone": {
    "h": 172,
    "s": 78,
    "v": 74
  },
  "team-genoa": {
    "h": 26,
    "s": 78,
    "v": 69
  },
  "team-inter": {
    "h": 226,
    "s": 42,
    "v": 57
  },
  "team-juventus": {
    "h": 0,
    "s": 0,
    "v": 0
  },
  "team-lazio": {
    "h": 67,
    "s": 37,
    "v": 90
  },
  "team-lecce": {
    "h": 201,
    "s": 55,
    "v": 59
  },
  "team-monza": {
    "h": 4,
    "s": 47,
    "v": 88
  },
  "team-napoli": {
    "h": 202,
    "s": 74,
    "v": 84
  },
  "team-parma": {
    "h": 26,
    "s": 46,
    "v": 69
  },
  "team-roma": {
    "h": 14,
    "s": 65,
    "v": 66
  },
  "team-sassuolo": {
    "h": 137,
    "s": 24,
    "v": 29
  },
  "team-torino": {
    "h": 15,
    "s": 60,
    "v": 72
  },
  "team-udinese": {
    "h": 51,
    "s": 15,
    "v": 31
  },
  "team-venezia": {
    "h": 41,
    "s": 53,
    "v": 59
  }
};
