// Generated by the visual scene build scripts. Values are measured from the
// original artwork and are the neutral anchor for the shared delta renderer.
export const BRAND_PAINT = {
  "facebook": {
    "h": 220,
    "s": 60,
    "v": 61
  },
  "amazon": {
    "h": 32,
    "s": 78,
    "v": 97
  },
  "pepsi": {
    "h": 356,
    "s": 82,
    "v": 89
  },
  "fanta": {
    "h": 236,
    "s": 65,
    "v": 56
  },
  "discord": {
    "h": 231,
    "s": 45,
    "v": 100
  },
  "steam": {
    "h": 214,
    "s": 81,
    "v": 42
  },
  "riot-games": {
    "h": 356,
    "s": 80,
    "v": 82
  },
  "nvidia": {
    "h": 82,
    "s": 100,
    "v": 73
  },
  "instagram": {
    "h": 20,
    "s": 76,
    "v": 97
  },
  "xbox": {
    "h": 108,
    "s": 89,
    "v": 64
  },
  "google": {
    "h": 217,
    "s": 73,
    "v": 96
  },
  "google-chrome": {
    "h": 44,
    "s": 77,
    "v": 100
  },
  "prime-video": {
    "h": 196,
    "s": 96,
    "v": 84
  },
  "carrefour": {
    "h": 213,
    "s": 100,
    "v": 54
  },
  "dominos": {
    "h": 355,
    "s": 81,
    "v": 87
  },
  "ebay": {
    "h": 211,
    "s": 100,
    "v": 82
  },
  "doritos": {
    "h": 5,
    "s": 96,
    "v": 78
  },
  "lays": {
    "h": 46,
    "s": 68,
    "v": 94
  },
  "cheetos": {
    "h": 50,
    "s": 92,
    "v": 98
  },
  "ruffles": {
    "h": 355,
    "s": 89,
    "v": 87
  },
  "fedex": {
    "h": 24,
    "s": 100,
    "v": 100
  },
  "ikea": {
    "h": 48,
    "s": 100,
    "v": 100
  },
  "intel": {
    "h": 206,
    "s": 100,
    "v": 77
  },
  "android": {
    "h": 76,
    "s": 81,
    "v": 75
  },
  "kfc": {
    "h": 354,
    "s": 83,
    "v": 76
  },
  "lacoste": {
    "h": 139,
    "s": 68,
    "v": 65
  },
  "twitter": {
    "h": 196,
    "s": 100,
    "v": 93
  },
  "twitch": {
    "h": 262,
    "s": 55,
    "v": 61
  },
  "subway": {
    "h": 57,
    "s": 100,
    "v": 100
  },
  "sprite": {
    "h": 209,
    "s": 97,
    "v": 63
  },
  "starbucks": {
    "h": 155,
    "s": 97,
    "v": 45
  },
  "spotify": {
    "h": 141,
    "s": 86,
    "v": 84
  },
  "shell": {
    "h": 49,
    "s": 97,
    "v": 98
  },
  "bp": {
    "h": 137,
    "s": 100,
    "v": 64
  },
  "apple": {
    "h": 34,
    "s": 86,
    "v": 97
  },
  "pepsi-globe": {
    "h": 0,
    "s": 96,
    "v": 100
  },
  "snickers": {
    "h": 222,
    "s": 78,
    "v": 64
  },
  "samsung": {
    "h": 212,
    "s": 98,
    "v": 64
  },
  "lg": {
    "h": 337,
    "s": 96,
    "v": 77
  },
  "rockstar-games": {
    "h": 39,
    "s": 100,
    "v": 100
  },
  "red-bull": {
    "h": 343,
    "s": 99,
    "v": 82
  },
  "popeyes": {
    "h": 20,
    "s": 89,
    "v": 100
  },
  "netflix": {
    "h": 0,
    "s": 100,
    "v": 75
  },
  "snapchat": {
    "h": 57,
    "s": 87,
    "v": 97
  },
  "mastercard": {
    "h": 32,
    "s": 92,
    "v": 98
  },
  "burger-king-round": {
    "h": 358,
    "s": 88,
    "v": 93
  },
  "visa": {
    "h": 207,
    "s": 100,
    "v": 62
  },
  "microsoft": {
    "h": 43,
    "s": 97,
    "v": 100
  },
  "monster-energy": {
    "h": 78,
    "s": 73,
    "v": 80
  },
  "lego": {
    "h": 359,
    "s": 92,
    "v": 81
  },
  "burger-king": {
    "h": 17,
    "s": 87,
    "v": 92
  },
  "mcdonalds": {
    "h": 46,
    "s": 100,
    "v": 100
  },
  "chupa-chups": {
    "h": 56,
    "s": 81,
    "v": 99
  },
  "coca-cola": {
    "h": 0,
    "s": 100,
    "v": 96
  },
  "youtube": {
    "h": 3,
    "s": 90,
    "v": 90
  }
};
export const TEAM_PAINT = {
  "team-augsburg": {
    "h": 2,
    "s": 72,
    "v": 73
  },
  "team-bayer-leverkusen": {
    "h": 0,
    "s": 100,
    "v": 97
  },
  "team-bayern-munich": {
    "h": 346,
    "s": 99,
    "v": 93
  },
  "team-borussia-dortmund": {
    "h": 51,
    "s": 100,
    "v": 99
  },
  "team-borussia-monchengladbach": {
    "h": 0,
    "s": 0,
    "v": 39
  },
  "team-eintracht-frankfurt": {
    "h": 357,
    "s": 98,
    "v": 88
  },
  "team-freiburg": {
    "h": 0,
    "s": 0,
    "v": 40
  },
  "team-hamburger-sv": {
    "h": 215,
    "s": 83,
    "v": 70
  },
  "team-hoffenheim": {
    "h": 212,
    "s": 85,
    "v": 71
  },
  "team-koln": {
    "h": 357,
    "s": 96,
    "v": 89
  },
  "team-mainz-05": {
    "h": 2,
    "s": 93,
    "v": 68
  },
  "team-paderborn": {
    "h": 212,
    "s": 86,
    "v": 72
  },
  "team-rb-leipzig": {
    "h": 344,
    "s": 95,
    "v": 87
  },
  "team-schalke-04": {
    "h": 211,
    "s": 99,
    "v": 61
  },
  "team-elversberg": {
    "h": 43,
    "s": 34,
    "v": 81
  },
  "team-union-berlin": {
    "h": 357,
    "s": 97,
    "v": 89
  },
  "team-vfb-stuttgart": {
    "h": 352,
    "s": 95,
    "v": 83
  },
  "team-werder-bremen": {
    "h": 154,
    "s": 99,
    "v": 51
  },
  "team-athletic-club": {
    "h": 1,
    "s": 85,
    "v": 93
  },
  "team-atletico-madrid": {
    "h": 358,
    "s": 90,
    "v": 91
  },
  "team-barcelona": {
    "h": 49,
    "s": 100,
    "v": 93
  },
  "team-celta-vigo": {
    "h": 346,
    "s": 100,
    "v": 84
  },
  "team-deportivo-alaves": {
    "h": 222,
    "s": 97,
    "v": 63
  },
  "team-deportivo-la-coruna": {
    "h": 44,
    "s": 39,
    "v": 72
  },
  "team-elche": {
    "h": 44,
    "s": 56,
    "v": 83
  },
  "team-espanyol": {
    "h": 0,
    "s": 90,
    "v": 88
  },
  "team-getafe": {
    "h": 203,
    "s": 98,
    "v": 67
  },
  "team-levante": {
    "h": 46,
    "s": 95,
    "v": 93
  },
  "team-malaga": {
    "h": 47,
    "s": 94,
    "v": 79
  },
  "team-osasuna": {
    "h": 45,
    "s": 65,
    "v": 80
  },
  "team-racing": {
    "h": 46,
    "s": 76,
    "v": 84
  },
  "team-rayo-vallecano": {
    "h": 53,
    "s": 75,
    "v": 74
  },
  "team-real-betis": {
    "h": 40,
    "s": 99,
    "v": 87
  },
  "team-real-madrid": {
    "h": 44,
    "s": 93,
    "v": 99
  },
  "team-real-sociedad": {
    "h": 44,
    "s": 86,
    "v": 90
  },
  "team-sevilla": {
    "h": 355,
    "s": 92,
    "v": 84
  },
  "team-valencia": {
    "h": 50,
    "s": 88,
    "v": 97
  },
  "team-villarreal": {
    "h": 48,
    "s": 80,
    "v": 99
  },
  "team-angers": {
    "h": 28,
    "s": 43,
    "v": 54
  },
  "team-monaco": {
    "h": 349,
    "s": 98,
    "v": 100
  },
  "team-auxerre": {
    "h": 216,
    "s": 81,
    "v": 62
  },
  "team-brest": {
    "h": 358,
    "s": 87,
    "v": 92
  },
  "team-le-havre-ac": {
    "h": 216,
    "s": 52,
    "v": 51
  },
  "team-le-mans": {
    "h": 358,
    "s": 95,
    "v": 85
  },
  "team-lille": {
    "h": 3,
    "s": 91,
    "v": 88
  },
  "team-lorient": {
    "h": 24,
    "s": 91,
    "v": 87
  },
  "team-lyon": {
    "h": 232,
    "s": 91,
    "v": 67
  },
  "team-nice": {
    "h": 43,
    "s": 53,
    "v": 70
  },
  "team-paris-fc": {
    "h": 202,
    "s": 95,
    "v": 70
  },
  "team-psg": {
    "h": 205,
    "s": 99,
    "v": 44
  },
  "team-rc-lens": {
    "h": 47,
    "s": 100,
    "v": 99
  },
  "team-rc-strasbourg-alsace": {
    "h": 199,
    "s": 99,
    "v": 86
  },
  "team-rennes": {
    "h": 4,
    "s": 82,
    "v": 88
  },
  "team-toulouse": {
    "h": 265,
    "s": 47,
    "v": 36
  },
  "team-troyes": {
    "h": 206,
    "s": 98,
    "v": 63
  },
  "team-arsenal": {
    "h": 358,
    "s": 99,
    "v": 90
  },
  "team-aston-villa": {
    "h": 54,
    "s": 97,
    "v": 99
  },
  "team-bournemouth": {
    "h": 358,
    "s": 91,
    "v": 76
  },
  "team-brentford": {
    "h": 357,
    "s": 96,
    "v": 88
  },
  "team-brighton": {
    "h": 207,
    "s": 99,
    "v": 67
  },
  "team-chelsea": {
    "h": 234,
    "s": 96,
    "v": 59
  },
  "team-coventry-city": {
    "h": 40,
    "s": 84,
    "v": 79
  },
  "team-crystal-palace": {
    "h": 209,
    "s": 97,
    "v": 65
  },
  "team-everton": {
    "h": 240,
    "s": 98,
    "v": 62
  },
  "team-fulham": {
    "h": 0,
    "s": 100,
    "v": 78
  },
  "team-hull-city": {
    "h": 33,
    "s": 98,
    "v": 92
  },
  "team-ipswich-town": {
    "h": 353,
    "s": 96,
    "v": 90
  },
  "team-leeds-united": {
    "h": 51,
    "s": 89,
    "v": 100
  },
  "team-liverpool": {
    "h": 357,
    "s": 88,
    "v": 90
  },
  "team-manchester-city": {
    "h": 212,
    "s": 80,
    "v": 56
  },
  "team-manchester-united": {
    "h": 358,
    "s": 99,
    "v": 83
  },
  "team-newcastle-united": {
    "h": 195,
    "s": 98,
    "v": 93
  },
  "team-nottingham-forest": {
    "h": 0,
    "s": 100,
    "v": 87
  },
  "team-sunderland": {
    "h": 355,
    "s": 88,
    "v": 90
  },
  "team-tottenham-hotspur": {
    "h": 227,
    "s": 78,
    "v": 34
  },
  "team-atalanta": {
    "h": 207,
    "s": 92,
    "v": 70
  },
  "team-bologna": {
    "h": 351,
    "s": 80,
    "v": 62
  },
  "team-cagliari": {
    "h": 351,
    "s": 90,
    "v": 69
  },
  "team-como": {
    "h": 207,
    "s": 84,
    "v": 42
  },
  "team-fiorentina": {
    "h": 271,
    "s": 61,
    "v": 55
  },
  "team-frosinone": {
    "h": 212,
    "s": 92,
    "v": 62
  },
  "team-genoa": {
    "h": 50,
    "s": 100,
    "v": 99
  },
  "team-inter": {
    "h": 227,
    "s": 99,
    "v": 61
  },
  "team-juventus": {
    "h": 0,
    "s": 0,
    "v": 0
  },
  "team-lazio": {
    "h": 39,
    "s": 77,
    "v": 84
  },
  "team-lecce": {
    "h": 219,
    "s": 62,
    "v": 39
  },
  "team-ac-milan": {
    "h": 349,
    "s": 100,
    "v": 88
  },
  "team-monza": {
    "h": 350,
    "s": 90,
    "v": 93
  },
  "team-napoli": {
    "h": 196,
    "s": 99,
    "v": 91
  },
  "team-parma": {
    "h": 49,
    "s": 99,
    "v": 99
  },
  "team-roma": {
    "h": 45,
    "s": 100,
    "v": 98
  },
  "team-sassuolo": {
    "h": 143,
    "s": 82,
    "v": 63
  },
  "team-torino": {
    "h": 6,
    "s": 77,
    "v": 55
  },
  "team-udinese": {
    "h": 50,
    "s": 60,
    "v": 55
  },
  "team-venezia": {
    "h": 25,
    "s": 100,
    "v": 100
  },
  "team-alanyaspor": {
    "h": 28,
    "s": 87,
    "v": 95
  },
  "team-antalyaspor": {
    "h": 357,
    "s": 84,
    "v": 92
  },
  "team-basaksehir": {
    "h": 205,
    "s": 99,
    "v": 54
  },
  "team-besiktas": {
    "h": 0,
    "s": 98,
    "v": 88
  },
  "team-bursaspor": {
    "h": 145,
    "s": 97,
    "v": 53
  },
  "team-corum": {
    "h": 359,
    "s": 94,
    "v": 82
  },
  "team-erzurumspor": {
    "h": 208,
    "s": 71,
    "v": 78
  },
  "team-eyupspor": {
    "h": 51,
    "s": 100,
    "v": 99
  },
  "team-fenerbahce": {
    "h": 56,
    "s": 98,
    "v": 97
  },
  "team-galatasaray": {
    "h": 35,
    "s": 88,
    "v": 97
  },
  "team-gaziantep": {
    "h": 3,
    "s": 79,
    "v": 85
  },
  "team-genclerbirligi": {
    "h": 357,
    "s": 96,
    "v": 88
  },
  "team-goztepe": {
    "h": 51,
    "s": 100,
    "v": 100
  },
  "team-kasimpasa": {
    "h": 226,
    "s": 71,
    "v": 65
  },
  "team-kayserispor": {
    "h": 43,
    "s": 89,
    "v": 98
  },
  "team-kocaelispor": {
    "h": 132,
    "s": 65,
    "v": 35
  },
  "team-konyaspor": {
    "h": 154,
    "s": 95,
    "v": 48
  },
  "team-rizespor": {
    "h": 1,
    "s": 83,
    "v": 94
  },
  "team-samsunspor": {
    "h": 359,
    "s": 93,
    "v": 78
  },
  "team-sivasspor": {
    "h": 351,
    "s": 99,
    "v": 86
  },
  "team-trabzonspor": {
    "h": 205,
    "s": 50,
    "v": 91
  }
};
