// Generated by the visual scene build scripts. Values are measured from the
// original artwork and are the neutral anchor for the shared delta renderer.
export const BRAND_PAINT = {
  "facebook": {
    "h": 220,
    "s": 51,
    "v": 67
  },
  "amazon": {
    "h": 32,
    "s": 12,
    "v": 30
  },
  "pepsi": {
    "h": 337,
    "s": 64,
    "v": 82
  },
  "fanta": {
    "h": 241,
    "s": 45,
    "v": 75
  },
  "discord": {
    "h": 231,
    "s": 45,
    "v": 100
  },
  "steam": {
    "h": 214,
    "s": 55,
    "v": 53
  },
  "riot-games": {
    "h": 356,
    "s": 80,
    "v": 82
  },
  "nvidia": {
    "h": 82,
    "s": 100,
    "v": 73
  },
  "instagram": {
    "h": 344,
    "s": 52,
    "v": 89
  },
  "xbox": {
    "h": 107,
    "s": 29,
    "v": 77
  },
  "google": {
    "h": 287,
    "s": 78,
    "v": 92
  },
  "google-chrome": {
    "h": 57,
    "s": 73,
    "v": 85
  },
  "prime-video": {
    "h": 196,
    "s": 79,
    "v": 65
  },
  "carrefour": {
    "h": 225,
    "s": 96,
    "v": 62
  },
  "dominos": {
    "h": 302,
    "s": 71,
    "v": 83
  },
  "ebay": {
    "h": 44,
    "s": 92,
    "v": 86
  },
  "doritos": {
    "h": 20,
    "s": 40,
    "v": 41
  },
  "lays": {
    "h": 22,
    "s": 41,
    "v": 93
  },
  "cheetos": {
    "h": 44,
    "s": 64,
    "v": 69
  },
  "ruffles": {
    "h": 12,
    "s": 75,
    "v": 87
  },
  "fedex": {
    "h": 341,
    "s": 91,
    "v": 73
  },
  "ikea": {
    "h": 59,
    "s": 100,
    "v": 80
  },
  "intel": {
    "h": 206,
    "s": 100,
    "v": 77
  },
  "android": {
    "h": 76,
    "s": 81,
    "v": 75
  },
  "kfc": {
    "h": 1,
    "s": 53,
    "v": 60
  },
  "lacoste": {
    "h": 138,
    "s": 67,
    "v": 66
  },
  "twitter": {
    "h": 196,
    "s": 100,
    "v": 93
  },
  "twitch": {
    "h": 262,
    "s": 55,
    "v": 61
  },
  "subway": {
    "h": 82,
    "s": 71,
    "v": 73
  },
  "sprite": {
    "h": 181,
    "s": 38,
    "v": 78
  },
  "starbucks": {
    "h": 155,
    "s": 55,
    "v": 68
  },
  "spotify": {
    "h": 141,
    "s": 86,
    "v": 84
  },
  "shell": {
    "h": 29,
    "s": 93,
    "v": 93
  },
  "bp": {
    "h": 106,
    "s": 89,
    "v": 77
  },
  "apple": {
    "h": 33,
    "s": 76,
    "v": 83
  },
  "pepsi-globe": {
    "h": 345,
    "s": 87,
    "v": 84
  },
  "snickers": {
    "h": 258,
    "s": 50,
    "v": 74
  },
  "samsung": {
    "h": 212,
    "s": 80,
    "v": 70
  },
  "lg": {
    "h": 337,
    "s": 81,
    "v": 80
  },
  "rockstar-games": {
    "h": 39,
    "s": 78,
    "v": 79
  },
  "red-bull": {
    "h": 355,
    "s": 66,
    "v": 90
  },
  "popeyes": {
    "h": 8,
    "s": 53,
    "v": 90
  },
  "netflix": {
    "h": 0,
    "s": 100,
    "v": 69
  },
  "snapchat": {
    "h": 57,
    "s": 59,
    "v": 93
  },
  "mastercard": {
    "h": 15,
    "s": 90,
    "v": 90
  },
  "burger-king-round": {
    "h": 8,
    "s": 86,
    "v": 86
  },
  "visa": {
    "h": 206,
    "s": 99,
    "v": 64
  },
  "microsoft": {
    "h": 59,
    "s": 94,
    "v": 91
  },
  "monster-energy": {
    "h": 95,
    "s": 49,
    "v": 47
  },
  "lego": {
    "h": 4,
    "s": 62,
    "v": 72
  },
  "burger-king": {
    "h": 17,
    "s": 86,
    "v": 92
  },
  "mcdonalds": {
    "h": 46,
    "s": 100,
    "v": 100
  },
  "chupa-chups": {
    "h": 37,
    "s": 69,
    "v": 90
  },
  "coca-cola": {
    "h": 0,
    "s": 100,
    "v": 96
  },
  "youtube": {
    "h": 3,
    "s": 71,
    "v": 72
  }
};
export const TEAM_PAINT = {
  "team-bayer-leverkusen": {
    "h": 22,
    "s": 48,
    "v": 74
  },
  "team-borussia-dortmund": {
    "h": 53,
    "s": 69,
    "v": 69
  },
  "team-bayern-munich": {
    "h": 320,
    "s": 58,
    "v": 88
  },
  "team-ajax": {
    "h": 353,
    "s": 5,
    "v": 81
  },
  "team-feyenoord": {
    "h": 12,
    "s": 31,
    "v": 55
  },
  "team-atletico-madrid": {
    "h": 317,
    "s": 41,
    "v": 64
  },
  "team-barcelona": {
    "h": 25,
    "s": 83,
    "v": 66
  },
  "team-real-madrid": {
    "h": 43,
    "s": 68,
    "v": 85
  },
  "team-sevilla": {
    "h": 16,
    "s": 42,
    "v": 83
  },
  "team-monaco": {
    "h": 23,
    "s": 55,
    "v": 85
  },
  "team-lyon": {
    "h": 28,
    "s": 58,
    "v": 84
  },
  "team-psg": {
    "h": 212,
    "s": 78,
    "v": 66
  },
  "team-arsenal": {
    "h": 3,
    "s": 72,
    "v": 78
  },
  "team-aston-villa": {
    "h": 54,
    "s": 52,
    "v": 83
  },
  "team-chelsea": {
    "h": 210,
    "s": 59,
    "v": 77
  },
  "team-liverpool": {
    "h": 26,
    "s": 49,
    "v": 77
  },
  "team-manchester-city": {
    "h": 205,
    "s": 42,
    "v": 81
  },
  "team-manchester-united": {
    "h": 24,
    "s": 92,
    "v": 80
  },
  "team-benfica": {
    "h": 36,
    "s": 48,
    "v": 70
  },
  "team-porto": {
    "h": 196,
    "s": 78,
    "v": 68
  },
  "team-ac-milan": {
    "h": 0,
    "s": 30,
    "v": 57
  },
  "team-as-roma": {
    "h": 14,
    "s": 65,
    "v": 66
  },
  "team-inter-milan": {
    "h": 226,
    "s": 42,
    "v": 57
  },
  "team-lazio": {
    "h": 67,
    "s": 37,
    "v": 90
  },
  "team-besiktas": {
    "h": 3,
    "s": 12,
    "v": 45
  },
  "team-fenerbahce": {
    "h": 39,
    "s": 37,
    "v": 74
  },
  "team-galatasaray": {
    "h": 26,
    "s": 31,
    "v": 94
  },
  "team-goztepe": {
    "h": 27,
    "s": 99,
    "v": 90
  },
  "team-kasimpasa": {
    "h": 224,
    "s": 60,
    "v": 77
  },
  "team-trabzonspor": {
    "h": 247,
    "s": 83,
    "v": 78
  }
};
